### ISSUE TITLE
Remove "sprints"

### ISSUE THREAD

**Issue by danielnixon** [agiledigital-labs/probabilistic-forecast#2]
Somewhat related to #1, we want to remove the concept of sprints from our output for kanban/lean Jira projects. We should instead just refer to "days"/"weeks"/"fortnights"/"months".

**Comment by shouvSarker** [comment]
Should we still present data like this substituting sprint with weeks or should we get rid of this type of insights?

```
Resolved 2 tickets in sprint 1.
Resolved 3 tickets in sprint 2.
Resolved 7 tickets in sprint 3.
Resolved 5 tickets in sprint 4.
Resolved 10 tickets in sprint 5.
```

**Comment by shouvSarker** [comment]
Thinking this may be a very sprint specific insight, so getting rid of it for now.

**Comment by shouvSarker** [comment]
Replacing it with a time interval (i.e. Resolved 2 tickets in 5 days (or any another custom timeframe))

**Comment by shouvSarker** [comment]
For time interval, currently implementing days and weeks (It would throw an error if user tries to do anything more funky)

**Comment by kn-ad** [comment]
> Should we still present data like this substituting sprint with weeks or should we get rid of this type of insights?
> 
> ```
> Resolved 2 tickets in sprint 1.
> Resolved 3 tickets in sprint 2.
> Resolved 7 tickets in sprint 3.
> Resolved 5 tickets in sprint 4.
> Resolved 10 tickets in sprint 5.
> ```

I think this works well when they're using the default time interval of one week:

```
Resolved 2 tickets in week 1.
Resolved 3 tickets in week 2.
...
```

Not sure what it should say if they're using something weird like 13 days. Maybe something like

```
Resolved 2 tickets between 2021-03-08 and 2021-03-21.
Resolved 3 tickets between 2021-02-23 and 2021-03-07.
...
```

Actually, that might be better in the default case as well. "Week 1" and "week 2" aren't very meaningful, especially if you're running the script regularly and saving the results. I'll split it out to a separate issue.

**Comment by shouvSarker** [comment]
PR got merged!
